### ISSUE TITLE
aggplot only accepts "agg" as normalize argument.

### ISSUE THREAD

**Issue by Idodox** [dexplo/dexplot#3]
when running 

dxp.aggplot(agg='interest_level', data = train_df, hue= "0_bathrooms", normalize = "col")

I get:
ValueError: `normalize` can only be None, "all", one of the values passed to  the parameter names "agg", "hue", "row", "col", or a combination of those parameter names in a tuple, if they are defined.

same error using any of my column names, "hue" "row" etc.

**Comment by tdpetrou** [comment]
Thank you for reporting this. I don't have time to improve the library now, but will do so later this year.

**Comment by tdpetrou** [comment]
@Idodox The library has been completely rebuilt with a slightly different API with all of these issues fixed and more.
