### ISSUE TITLE
Order for 'agg' and 'hue' parameters when set to strings/categorical variables

### ISSUE THREAD

**Issue by rinkalaone** [dexplo/dexplot#4]
I think this package is awesome, really improving seaborn.countplot for displaying proportions, for example, but it's seems it is not possible to pass along an order for categorical variables, like order= or hue_order for barplot/countplot. That is something that is very important to be able to do, or am I missing something?
 many greeting, Karine

**Comment by tdpetrou** [comment]
Thanks! Try making the columns am ordered `CategoricalDtype` in pandas first.  I believe that should do it.

Also, I have not worked on this in a long time, but hope to have a more complete package together by the end of 2020.

**Comment by tdpetrou** [comment]
@rinkalaone The library has been rebuilt with a different API. All of these issues are now fixed.

**Comment by rinkalaone** [comment]
@tdpetrou Sounds great! I'll check that out. Thanx
