### ISSUE TITLE
Dexplot in Spyder with Python3.7

### ISSUE THREAD

**Issue by Alex18590** [dexplo/dexplot#9]
Hi Sir,

Great job,
I am using dexplot on spyder, I can save the plot but it is not possible to see any dxp plot in the Plots window.
In addition, is it possible to use dxp with plt.subplots to combine multiples plots? I am trying but I am not able.

**Comment by tdpetrou** [comment]
I'm not sure how spyder works, so I can't comment on how to make it show in the plots window. All dexplot plots return the matplotlib figure instance, so if you can put a matplotlib figure in that window, you should be able to put a dexplot plot as well.

Regarding multiple plots - you can extract the Axes from each plot like this:

fig = dxp.some_plot()
ax = fig.axes[0]
